language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_91f4af6b9b05_key -iv $encrypted_91f4af6b9b05_iv
  -in deploy_key.enc -out deploy_key -d
- npm install -g grunt-cli
install:
- npm install
script:
- echo 'Nothing to do for script.'
after_success:
- grunt
- pwd
- ls -la
- chmod 600 deploy_key
- ssh-add deploy_key
- echo '12.200.178.238 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0HnQv787AYPAHvXrGiZgWc3oiML1R6yWAdZ0YslNGO354xhivDWh285NwnAszRz2nRBWOQHl96YJLoDEa3bUrRV6vgFmGgAcewMxSoJ8hx8K5U6Ylcoqh38DtWGJwwwFjp9+6X/R9IxA263NJuujfFNogP2TDWVLnL8XVOlyzdrV1/OVxOVnEsETuniZ9sy3SkYBjB5KN48a1HF2Fbkj95E58RgXRYOxdqt8WgXDIiNbAtb8HsYFpXfn1SqKmSdTApBYRCd7A8hJIu0zwcPFuCDxidxbd5XU6iMcCg6J3mS1YHrayeyJRurEXYRAYnQ5HZAhtPEtDL1C+zWTvHdSMQ==' >> ~/.ssh/known_hosts
- ssh -p 55713 ejcarron@12.200.178.238 'pwd'
