language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
before_install:
- "echo 'Nothing to do before install.'"
install:
- "echo 'Nothing to do for install.'"
script:
- "echo 'Nothing to do for script.'"
before_deploy:
- "echo 'Nothing to do before deploy.'"
deploy:
  provider: script
  skip_cleanup: true
  script: deploy/deploy.sh
