language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
before_install:
- npm install -g grunt-cli
install:
- npm install
script:
- "echo 'Nothing to do for script.'"
after_success:
- grunt
- pwd
- ls -la
