language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_91f4af6b9b05_key -iv $encrypted_91f4af6b9b05_iv
  -in deploy_key.enc -out deploy_key -d
- npm install -g grunt-cli
install:
- npm install
script:
- echo 'Nothing to do for script.'
after_success:
- grunt
- pwd
- ls -la
- chmod 600 deploy_key
- ssh-add deploy_key
- ssh -p 55713 ejcarron@12.200.178.238 'pwd'
